DEBUG 2025-04-02 10:11:16.803 UTC: 	 CRAB Client version: v3.250318
DEBUG 2025-04-02 10:11:16.804 UTC: 	 Running on: Linux private-snu 6.13.8-200.fc41.x86_64 #1 SMP PREEMPT_DYNAMIC Sun Mar 23 05:03:09 UTC 2025 x86_64 x86_64 x86_64 GNU/Linux
DEBUG 2025-04-02 10:11:16.804 UTC: 	 Using SINGULARITY image: private-el9.sif
DEBUG 2025-04-02 10:11:16.804 UTC: 	 Operating System: AlmaLinux 9.5 (Teal Serval)
DEBUG 2025-04-02 10:11:16.804 UTC: 	 Executing command: 'status'
DEBUG 2025-04-02 10:11:16.804 UTC: 	 Found CRAB cache file /home/choij/.crab3
ERROR 2025-04-02 10:11:16.804 UTC: 	 Error: crab_projects/crab_DY0j_LO_5f_LEGACY is not a valid CRAB project directory.
ERROR 2025-04-02 10:11:16.804 UTC: 	 Caught ClientException exception
Traceback (most recent call last):
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.250318.00/bin/crab.py", line 157, in <module>
    client()
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.250318.00/bin/crab.py", line 135, in __call__
    self.cmd = sub_cmd(self.logger, args[1:])  # the crab command to be executed
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.250318.00/lib/CRABClient/Commands/status.py", line 48, in __init__
    SubCommand.__init__(self, logger, cmdargs)
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.250318.00/lib/CRABClient/Commands/SubCommand.py", line 281, in __init__
    SubCommand.validateOptions(self)
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.250318.00/lib/CRABClient/Commands/SubCommand.py", line 691, in validateOptions
    raise ConfigurationException(msg)
CRABClient.ClientExceptions.ConfigurationException: [91mError[0m: crab_projects/crab_DY0j_LO_5f_LEGACY is not a valid CRAB project directory.
INFO 2025-04-02 10:11:16.806 UTC: 	 Log file is /home/choij/workspace/CustomNanoGEN_CMSSW_13_0_13/src/Configuration/CustomNanoGEN/crab.log
